name = input("Enter your full name: ")
length = len(name)
print(length)
find_result_first = name.find(" ")
print(find_result_first)
find_result_last = name.rfind("s")
print(find_result_last)
print(name.capitalize())
print(name.upper())
print(name.lower())
print(name.isdigit())
print(name.isalpha())

phone_number = input("Enter your phone number: ")
print(phone_number.count('9'))
print(phone_number.replace('9','0'))
